blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Sorostack/stellar-payments-kit/docs
    about: Check the docs before filing an issue
  - name: Security
    url: https://github.com/Sorostack/stellar-payments-kit/SECURITY.md
    about: Report security issues privately
